import Image from "next/image"
import Header from "../components/header"
import Footer from "../components/footer"
import Navbar from "../components/navbar"
import Head from 'next/head'
export default function Dedication() {
    return (
        <div>
            <Head>
                <title>Just like Grandma's</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/NancyPhotos/cookbook.gif" />
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Galada&display=swap" rel="stylesheet"/>
            </Head>
            <Header/>
            <Navbar/>
            <main class="grid">
                <div class="dedication">
                    <h1>Dedicated to Nancy Ferguson</h1>
                    <h4>Grandmother, Provider, and a source of Joy</h4>
                    <p>Nancy Ferguson is a mother to three. Grandmother to seven. Married over fifty years.<br/>An amazing cook, a wonderful quilter, and the start of many happy memories</p>
                    <p>I would like to dedicate this website to my amazing grandmother, Nancy Ferguson. She was a wonderful cook, quilter, loving mother of 3, and grandmother of 7.
                        She bravly battled brain cancer, but she has never lost her sassy and joyful personality. We love her so much and are greatful for all the time we had together.
                    </p>
                </div>
                <div class="gallery2">
                    <Image src="/NancyPhotos/Grandparents.jpg" 
                        id="Grandparents"
                        width="500"
                        height="300"/>
                    <h3 id="text1">Robert and Nancy Ferguson</h3>
                    <Image src="/NancyPhotos/Family2017.jpg" 
                        id="Family2017"
                        width="500"
                        height="300"/>
                    <h3 id="text2">Grandparents with three eldest Granddaughters</h3>
                    <Image src="/NancyPhotos/Easter.jpg" 
                        id="Easter"
                        width="500"
                        height="300"/>
                    <h3 id="text3">Dying Easter Egss</h3>
                    <Image src="/NancyPhotos/Dad'sbirthday.png" 
                        id="Dad"
                        width="500"
                        height="300"/>
                    <h3 id="text4">Celebrating Birthday with Family</h3>
                </div>
            </main>
            <Footer/>
        </div>
    )
}