import Image from "next/image"
import Header from "../components/header"
import Footer from "../components/footer"
import Navbar from "../components/navbar"
import Head from 'next/head'
export default function Dedication() {
    return (
        <div>
            <Head>
                <title>Just like Grandma's | Dedication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/NancyPhotos/cookbook.gif" />
            </Head> 
            <Header/>
            <Navbar/>
            <main >
                <div className="dedication">
                    <h1>Dedicated to Nancy Ferguson</h1>
                    <h4>Grandmother, Provider, and a source of Joy</h4>
                    <p>This website is dedicated to my amazing grandmother, Nancy Ferguson. She was a wonderful cook, quilter, loving mother of 3, and grandmother of 7.
                        She lost the battle against brain cancer, but she never lost her sassy and joyful personality. We love her so much and are grateful for all the time we had together.
                    </p>
                </div>
                <div className="gallery2">
                    <div>
                    <Image src="/NancyPhotos/Grandparents.jpg" 
                        alt="Robert and Nancy Ferguson"
                        id="Grandparents"
                        width="576"
                        height="577"/>
                    <h3 id="text1">Robert and Nancy Ferguson</h3>
                    </div>
                    <div>
                    <Image src="/NancyPhotos/Family2017.jpg" 
                        alt="Grandparents with three eldest Granddaughters"
                        id="Family2017"
                        width="640"
                        height="577"/>
                    <h3 id="text2">Grandparents with three eldest Granddaughters</h3>
                    </div>
                    <div>
                    <Image src="/NancyPhotos/Easter.jpg" 
                        alt="two small girls Dying Easter Eggs with grandmother"
                        id="Easter"
                        width="506"
                        height="334"
                        />
                    <h3 id="text3">Dying Easter Eggs</h3>
                    </div>
                    <div>
                    <Image src="/NancyPhotos/Dad'sbirthday.png" 
                        alt="two small girls bery excited to help dad with candles on cake"
                        id="Dad"
                        width="540"
                        height="387"
                        />
                    <h3 id="text4">Celebrating Birthday with Family</h3>
                    </div>
                </div>
            </main>
            <Footer/>
        </div>
    )
}