import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Navbar from '../components/navbar'
import Samples from '../components/samples'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Just like Grandma&#39;s | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NancyPhotos/cookbook.gif" />
      </Head>

        <Header/>
        <Navbar/>
      <div>
        <div className="advert">
            <h2>Order the <span className="italic">Just like Grandma&#39;s</span> official cookbook.</h2>
            <h2 id="sale">On Sale Now!!!</h2>
        </div>
        <div id="floatright">
            <p className="testimonies">&#34;Just like Grandma used to make&#34; - Granddaughter</p>
            <Image 
              src="/NancyPhotos/6thBday.png" 
              alt='Brown headed girl in front of Tinkerbell birthday cake'
              id="bday"
              priority="true"
              width="611"
              height="467"
            />
        </div>
        <div id="floatleft">
            <p className="testimonies">&#34;It makes me feel like she&#39;s still here with us&#34; - Grandson</p>
        
            <Image 
              src="/NancyPhotos/CousinCaty.jpg"
              alt='girl in pink shirt holding brothers birthday cake'
              id="cousin"
              width="600"
              height="467"
            />
        </div>
        <div  id="legacy">
            <p className="testimonies">&#34;A legacy to pass on for generations&#34; - Son</p>
          </div>
      </div>
      <Samples/>
      <Footer/>
    </div>
  )
}
