import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Navbar from '../components/navbar'
import Samples from '../components/samples'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Just like Grandma's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NancyPhotos/cookbook.gif" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Galada&display=swap" rel="stylesheet"/>
      </Head>

        <Header/>
        <Navbar/>
      <div>
        <div className="advert">
            <h2>Order the <span class="italic">Just like Grandma's</span> official cookbook.</h2>
            <h2 id="sale">On Sale Now!!!</h2>
        </div>
        <div id="floatright">
            <p className="testimonies">"Just like Grandma used to make" - Granddaughter</p>
            <Image 
              src="/NancyPhotos/6thBday.png" 
              id="bday"
              width="500"
              height="300"/>
        </div>
        <div id="floatleft">
            <p className="testimonies">"It makes me feel like she's still here with us" - Grandson</p>
        
            <Image 
              src="/NancyPhotos/CousinCaty.jpg" 
              id="cousin"
              width="500"
              height="300"/>
        </div>
        <div  id="legacy">
            <p className="testimonies">"A legacy to pass on for generations" - Son</p>
          </div>
      </div>
      <Samples/>
      <Footer/>
    </div>
  )
}
