import Chicken from "../components/chickenAndRiceCassorole";
import Header from "../components/header"
import Navbar from "../components/navbar"
import Image from "next/image";
import Sugar from "../components/sugarcookies";
import Icing from "../components/royalIcing"
import Waffles from "../components/waffles"
import Footer from "../components/footer";
import Head from 'next/head'

export default function Recipies() {
    return (
        <div>
            <Head>
                <title>Just like Grandma's</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/NancyPhotos/cookbook.gif" />
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Galada&display=swap" rel="stylesheet"/>
            </Head>
            <Header/>
            <Navbar/>
            <div class="gallery">
                <Image 
                    src="/NancyPhotos/Christmas.jpg" 
                    id="Christmas"
                    width="500"
                    height="300"/>
                <Image 
                    src="/NancyPhotos/Valentines.jpg" 
                    id="Valentines"
                    width="500"
                    height="300"/>
                <Image 
                    src="/NancyPhotos/Snickerdoddles.jpg" 
                    id="Snickerdoddles"
                    width="500"
                    height="300"/>
            </div>
            <Chicken/>
            <Sugar/>
            <Icing/>
            <Waffles/>
            <Footer/>
        </div>
    )
}