import Chicken from "../components/chickenAndRiceCassorole";
import Header from "../components/header"
import Navbar from "../components/navbar"
import Image from "next/image";
import Sugar from "../components/sugarcookies";
import Icing from "../components/royalIcing"
import Waffles from "../components/waffles"
import Footer from "../components/footer";
import Head from 'next/head'

export default function Recipies() {
    return (
        <div>
            <Head>
                <title>Just like Grandma&#39;s | Free Recipes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/NancyPhotos/cookbook.gif" />
            </Head>
            <Header/>
            <Navbar/>
            <h1 id="free">Free Recipes</h1>
            <div className="gallery">
                <Image 
                    src="/NancyPhotos/Christmas.jpg" 
                    alt="Christmas themed sugar cookies"
                    id="Christmas"
                    priority="true"
                    width="500"
                    height="300"
                     />
                <Image 
                    src="/NancyPhotos/Valentines.jpg" 
                    alt="Valentines themed sugar cookies"
                    id="Valentines"
                    width="500"
                    height="300"
                    />
                <Image 
                    src="/NancyPhotos/Snickerdoddles.jpg" 
                    alt="snickerdoodles on a pan"
                    id="Snickerdoodles"
                    width="500"
                    height="300"
                />
            </div>
            <div className="flexbox">
            <Chicken/>
            <Sugar/>
            <Icing/>
            <Waffles/>
            </div>
            <Footer/>
        </div>
    )
}